In [1]:
import numpy as np

# Data Manipulation with NumPy

## Introduzione
Manipolazione dei dati usando la libreria di numpy

### Data Processing
L'uso universale dei dati rende l'elaborazione dei dati, l'atto di convertire i dati grezzi in una forma significativa, un'abilità essenziale da avere.

### Numpy
Molti scenari coinvolgono principalmente set di dati numerici.
<br>La maggior parte delle reti neurali utilizza dati di input numerici o convertiti in una forma numerica.
<br><br>Quando abbiamo a che fare con dati numerici, la migliore libreria di py è **NumPy** che ci consente di eseguire molte operazioni sui dati numerici e convertire i dati in moduli più utilizzabili

In [2]:
import numpy as np  # import the NumPy library

# Initializing a NumPy array
arr = np.array([-1, 2, 5], dtype=np.float32)

# Print the representation of the array
print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


## NumPy Arrays

### Arrays
Gli array di NumPy sono liste Python ma con funzionalità aggiuntive.<br>
Per effettuare la conversione si può utilizzare la funzione `np.array`.<br>
Un parametro da tenere in considerazione è `dtype`. Con questo comando si pu; effettuare il cast di un array.

In [3]:
arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)

print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


Quando gli elementi di una matrice NumPy sono tipo misto il tipo dell'array verrà reindirizzato al tipo di livello più alto.
- Nel caso ci siano elementi di formato `int` e `float`, tutti gli elementi `int` verranno convertiti ai loro corrispettivi in `float`.
- Invece nel caso in cui un array contenga elementi di tipo `int`, `float` e `string` verranno convertiti tutti in formato `string`.

In [4]:
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


### Copying
Similmente agli array di Python, quando si fa riferimento a un array NumPy non ne crea una diverso. Quindi se cambiamo un valore usando la variabile di riferimento, verrà cambiato l'originale.<br><br>
La funzione `copy` invece non necessita di argomenti e restituisce una copia dell'array.<br><br>
Nel primo esempio viene effettuata la modifica sull'array originale mentre sul secondo no.

In [5]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


### Casting
Si può castare un array NumPy attraverso la funzione `astype`. Come argomento questa funzione richiede il nuovo tipo per l'array.
<br><br>
L'esempio che segue mostra un esempio di cating usando la funzione `astype`. Il modulo `dtype` restituisce il tipo dell'array.

In [6]:
arr = np.array([0, 1, 2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int32
float32


### NaN
Quando non si vuole che un array NumPy contenga un valore in un particolare indice, si può utilizzare `np.nan` che funge da segnaposto. Un uso comune di `np.nan` è come valore di riempimento per i dati incompleti.
<br><br>L'esempio mostra un caso di utilizzo di `np.nan`. `np.nan` non può assumere un tipo `int`. 

In [7]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError: If we uncomment line 8 and run again.
#np.array([np.nan, 1, 2], dtype=np.int32)
np.array([np.nan, 1, 2], dtype=np.float32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


array([nan,  1.,  2.], dtype=float32)

### Infinity
Per rappresentare infinito in NumPy, si usa il valore speciale `np.inf`. Si può rappresentare anche -infinito con `-np.inf`.
<br><br>L'esempio mostra un caso di utilizzo di `np.inf`. `np.nan` non può assumere un tipo `np.inf`.

In [8]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in a OverflowError: If we uncomment line 10 and run again.
#np.array([np.inf, 3], dtype=np.int32)
np.array([np.inf, 3], dtype=np.float32)

True
array([inf,  5.])
array([-inf,   1.])


array([inf,  3.], dtype=float32)

### Time to Code!

Array:
- interi e np.nan
- `np.nan` come primo elemento
- `2`, `3`, `4`, `5` fino alla quarta posizione

In [9]:
arr = np.array([np.nan, 2, 3, 4, 5])

- copiare l'array per modificare il primo elemento in `10`

In [10]:
arr2 = arr.copy()
arr2[0] = 10
arr2

array([10.,  2.,  3.,  4.,  5.])

- Imposta il `float_arr` a `np.array` con gli elementi `1`, `5.4` e `3`
- Imposta `float_arr2` con argomento `np.float32`

In [11]:
float_arr = np.array([1, 5.4, 3])
float_arr2 = arr2.astype(np.float32)
float_arr2

array([10.,  2.,  3.,  4.,  5.], dtype=float32)

- imposta `matrice` uguale a `np.array` con una lista di liste come primo argomento e `np.float32`come argomento di `dtype`

In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6]],
                  dtype=np.float32)
matrix

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

## NumPy Basics

### Ranged data

`np.array` non può funziona per array con centinaia di valori. <br>NumPy fornisce un'opzione per creare matrici di dati a distanza usando `np.arange` Il concetto è quello della funzione `range` di Python e restituirà un array 1D.

In [13]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


Gli output di `np.arange` sono:
- se come argomento viene passato un singolo numero `np.arange` restituirà una matrice con tutti numeri interi nell'intervalo [0, n)
- se vengono passati due interi come argomenti `np.arange`restituirà una matrice con tutti gli interi nell'intervallo [m, n)
- se vengono passati 3 argomenti `np.arange` restituirà tutti gli interi nell'intervallo [m, n) usando uno step s.
- come `np.array`, `np.arange` esegue l'upcasting. Ha anche la keyword `dtype` per effettuare il cast manualmente.

Per specificare il numero di elementi nella matrice restituita, anzichè la dimensione dello step, è possibile utilizzare la funzione `np.linspace`.
<br><br>La fine del range è incluso per `np.linspace` a meno che l'argomento della keyword sia impostato su `False`. Per specificare il numero di elementi, si setta la keyword `num` (di default `50`)

In [14]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11])


### Reshaping data

La funzione che si usa per rimodellare i dati in NumPy è `np.reshape`.
<br>Assume una matrice e una nuova forma come argomenti richiesti. La nuova forma deve contenere esattamente tutti gli elementi nella matrice di input.
<br><br>E' permesso utilizzare il valore speciale `-1` per una dimensione massima della nuova forma.

In [15]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


Mentre `np.reshape` può eseguire qualsiasi utilità di rimodellamento di cui abbiamo bisogno, NumPy fornisce una funzione intrinseca per appiattire un array.
<br><br>L'esempio seguente "appiattisce" la matrice con funzione `flatten`.

In [16]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


### Transposing
E' anche possibile trasporre i dati con la funzione `np.transpose`. Le righe della matrice diventano le colonne dopo la trasposizione.

In [17]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


La funzione `np.transpose` accetta un primo argomento richiesto, che sarà l'array che si vuole trasporre. La keyword `axes` che rappresenta la nuova permutazione delle dimensioni.
<br><br>La permutazione è una tupla/lista di numeri interi, con la stessa lunghezza del numero di dimensioni nella matrice.

In [18]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
transposed = np.transpose(arr, axes=(1, 2, 0))
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))

arr shape: (3, 4, 2)
transposed shape: (4, 2, 3)


In questo esempio:
- la prima vecchia dimensione è diventata la nuova terza dimensione,
- la seconda vecchia dimensione è diventata la nuova prima dimensione e 
- la terza vecchia dimensione è diventata la nuova seconda dimensione.

Il valore di default per `axes` è un'inversione di dimensione:
- per esempio per gli array 3D il valore predefinito di `axes` è `[2,1,0].`

### Zeros and ones
Potrebbe essere necessario generare array esclusivamemte con 0 e 1 per creare set di dati fittizi rigorosamente di un'etichetta.<br>
Per creare questi array, NumPy ha le funzioni `np.zeros` e `np.ones`. <br>Entrambe hanno un solo argomento, la forma dell'array. La funzione permette anche il casting manuale usando `dtype`.

In [19]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]])


Se si vuole creare una matrice di 0 e 1 con la stessa forma di un'altra matrice, si può usare `np.zeros_like` and `np.ones_like`.

In [20]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]])


### Time to Code!

- setta `arr` uguale a `np.arange` uguale a `12`
- poi setta `reshaped` uguale a `np.reshape` con `arr` come primo argomento e `(2, 3, 2)` come secondo argomento

In [21]:
arr = np.arange(12)
reshaped = np.reshape(arr, (2, 3, 2))
reshaped

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

- setta `reshaped` come `flattened`

In [22]:
flattened = reshaped.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- setta `transposed` uguale a `np.transpose` con `reshape` come primo argomento e la permutazione specificata per l'argomento della keyword `axes`.

In [23]:
transposed = np.transpose(reshaped, axes=(1, 2, 0))
transposed

array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])

- creare un array con 5 `0`
- creare un array con la stessa forma di `transposed` ma contenente solo `1` come elementi

In [24]:
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [25]:
ones_arr = np.ones_like(transposed)
ones_arr

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

- setta points uguale a `np.linspace` con `-3.5` e `1.5` come primo e secondo argomento e `101` per l'argomento `num`

In [26]:
points = np.linspace(-3.5, 1.5, num=101)
points

array([-3.5 , -3.45, -3.4 , -3.35, -3.3 , -3.25, -3.2 , -3.15, -3.1 ,
       -3.05, -3.  , -2.95, -2.9 , -2.85, -2.8 , -2.75, -2.7 , -2.65,
       -2.6 , -2.55, -2.5 , -2.45, -2.4 , -2.35, -2.3 , -2.25, -2.2 ,
       -2.15, -2.1 , -2.05, -2.  , -1.95, -1.9 , -1.85, -1.8 , -1.75,
       -1.7 , -1.65, -1.6 , -1.55, -1.5 , -1.45, -1.4 , -1.35, -1.3 ,
       -1.25, -1.2 , -1.15, -1.1 , -1.05, -1.  , -0.95, -0.9 , -0.85,
       -0.8 , -0.75, -0.7 , -0.65, -0.6 , -0.55, -0.5 , -0.45, -0.4 ,
       -0.35, -0.3 , -0.25, -0.2 , -0.15, -0.1 , -0.05,  0.  ,  0.05,
        0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,  0.5 ,
        0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,  0.95,
        1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,  1.35,  1.4 ,
        1.45,  1.5 ])

## Math

### Arithmetic
Uno degli scopi principali di NumPy è quello di eseguire l'aritmetica su array multidimensionali. <br>Utilizzando le matrici NumPy, possiamo applicare l'aritmetica a ciascun elemento con una singola operazione.

In [27]:
arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))

array([[2, 3],
       [4, 5]])


In [28]:
# Subtract element values by 1.2
print(repr(arr - 1.2))

array([[-0.2,  0.8],
       [ 1.8,  2.8]])


In [29]:
# Double element values
print(repr(arr * 2))

array([[2, 4],
       [6, 8]])


In [30]:
# Halve element values
print(repr(arr / 2))

array([[0.5, 1. ],
       [1.5, 2. ]])


In [31]:
# Integer division (half)
print(repr(arr // 2))

array([[0, 1],
       [1, 2]], dtype=int32)


In [32]:
# Square element values
print(repr(arr**2))

array([[ 1,  4],
       [ 9, 16]], dtype=int32)


In [33]:
# Square root element values
print(repr(arr**0.5))

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


Utilizzando l'aritmetica di NumPy, si può facilmente modificare grandi quantità di dati numerici con poche operazioni. 
- Ad esempio, si potrebbe convertire un set di dati di temperature Fahrenheit nella loro forma Celsius equivalente.

In [34]:
def f2c(temps):
    return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

Celsius: array([  0., -20., -10., -40.])


L'esecuzione dell'aritmetica su matrici NumPy **non modifica la matrice originale** e produce invece una nuova matrice risultante dall'operazione aritmetica.

### Non-linear functions

La funzione:
- `np.exp` esegue un esponenziale in base `e` su un array, 
- `np.exp2` esegue un esponenziale in base `2`. 

Allo stesso modo, `np.log`, `np.log2` e `np.log10` eseguono tutti logaritmi su un array di input, utilizzando rispettivamente la base `e`, la base `2` e la base `10`.

pigreco = `np.pi`

In [35]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [36]:
# Raised to power of e
print(repr(np.exp(arr)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])


In [37]:
# Raised to power of 2
print(repr(np.exp2(arr)))

array([[ 2.,  4.],
       [ 8., 16.]])


In [38]:
arr2 = np.array([[1, 10], [np.e, np.pi]])
arr2

array([[ 1.        , 10.        ],
       [ 2.71828183,  3.14159265]])

In [39]:
# Natural logarithm
print(repr(np.log(arr2)))

array([[0.        , 2.30258509],
       [1.        , 1.14472989]])


In [40]:
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


Per elevare a potenza con ogni base, si usa `np.power`. Il primo argomento della funzione è la base, mentre il secondo è la potenza. Può essere applicata a un'intera matrice.

In [41]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [42]:
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))

array([[ 3,  9],
       [27, 81]], dtype=int32)


In [43]:
arr2 = np.array([[10.2, 4], [3, 5]])
arr2

array([[10.2,  4. ],
       [ 3. ,  5. ]])

In [44]:
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 10.2,  16. ],
       [ 27. , 625. ]])


https://numpy.org/doc/stable/reference/routines.math.html

### Matrix multiplication
Poiché gli array NumPy sono vettori e matrici, ci sono funzioni per i prodotti a punti e la moltiplicazione delle matrici.
<br>La funzione principale da usare è `np.matmul` che prende due array vettoriali/matrici come input e produce un prodotto punto o una moltiplicazione matriciale.

In [45]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

27


In [46]:
arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
# This will result in a ValueError: If we uncomment line 10 and run again.
#print(repr(np.matmul(arr3, arr3)))

array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


### Time to Code!

In [47]:
arr = np.array([[-0.5, 0.8, -0.1], [0.0, -1.2, 1.3]])
arr2 = np.array([[1.2, 3.1], [1.2, 0.3], [1.5, 2.2]])

- setta `multiplied` uguale a arr moltiplicato per `np.pi`
- setta `added` uguale al risultato dell'aggiunta `arr` e `multiplied`
- setta `squared` uguale a `add` con ogni suo elemento al quadrato

In [48]:
arr

array([[-0.5,  0.8, -0.1],
       [ 0. , -1.2,  1.3]])

In [49]:
multiplied = arr * np.pi
multiplied

array([[-1.57079633,  2.51327412, -0.31415927],
       [ 0.        , -3.76991118,  4.08407045]])

In [50]:
added = arr + multiplied
added

array([[-2.07079633,  3.31327412, -0.41415927],
       [ 0.        , -4.96991118,  5.38407045]])

In [51]:
squared = added**2
squared

array([[ 4.28819743, 10.97778541,  0.1715279 ],
       [ 0.        , 24.70001718, 28.98821461]])

- setta `exponential` uguale a `np.exp` applicato a `squared`
- setta `logged` uguale a `np.log` applicato a `arr2`

In [52]:
exponential = np.exp(squared)
exponential

array([[7.28350596e+01, 5.85587272e+04, 1.18711726e+00],
       [1.00000000e+00, 5.33434578e+10, 3.88527393e+12]])

In [53]:
logged = np.log(arr2)
logged

array([[ 0.18232156,  1.13140211],
       [ 0.18232156, -1.2039728 ],
       [ 0.40546511,  0.78845736]])

- setta `matmul1` uguale a `np.matmul` con primo argomento `logged` e secondo argomento `exponential`

In [54]:
matmul1 = np.matmul(logged, exponential)
matmul1

array([[ 1.44108036e+01,  6.03529115e+10,  4.39580713e+12],
       [ 1.20754286e+01, -6.42240618e+10, -4.67776415e+12],
       [ 3.03205327e+01,  4.20590657e+10,  3.06337283e+12]])

- setta `matmul2` uguale a `np.matmul` con primo argomento `exponential` e secondo argomento `logged`

In [55]:
matmul2 = np.matmul(exponential, logged)
matmul2

array([[ 1.06902790e+04, -7.04197733e+04],
       [ 1.58506868e+12,  2.99914875e+12]])

## Random

### Random integers
Simile al modulo di Python `random`, NumPy ha il suo modulo `np.random`.<br>
Fornisce tutte le operazioni randomizzate necessarie e le estende a matrici multidimensionali.
<br>Per generare numeri interi si usa la funzione `np.random.randint`.

In [56]:
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14,
                               size=(2, 2))
print(repr(random_arr))

2
2
5
array([[12,  1],
       [12,  4]])


La funzione `np.random.randint` accetta un singolo argomento richiesto, che dipende dall'argomento della keyword `high`. 
- Se `high=None` l'argomento richiesto rappresenta l'estremità superiore dell'intervallo, esclusa, con estremità inferiore uguale a 0. <br>L'intero casuale è scelto all'intervallo [0,n)
- Se non `high=None` l'argomento richiesto rappresenterà l'estremità inferiore (inclusiva) dell'intervallo, mentre `high` rappresenta l'estremità superiore (esclusiva).

`size` definisce quanti devono essere i numeri estratti casualmente

### Utility functions
Alcune funzioni di utilità fondamentali del modulo `np.random` sono:
- `np.random.seed` 
- e `np.random.shuffle`. 

Si la funzione `np.random.seed` per impostare il seme casuale, che ci permette di controllare gli output delle funzioni pseudo-casuali. La funzione accetta un singolo intero come argomento.

Il codice seguente usa `np.random.seed` con lo stesso seme casuale. Gli output delle funzioni casuali in ogni esecuzione successiva sono identici quando si imposta lo stesso seme casuale.

In [57]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])


In [58]:
# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

8
array([[18, 75],
       [25, 46]])


In [59]:
# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])


La funzione `np.random.shuffle` consente di mescolare casualmente un array. Si noti che il rimescolamento avviene sul posto e il rimescolamento di array multidimensionali mescola solo la prima dimensione.

Il codice seguente mostra gli utilizzi di esempio di `np.random.shuffle`. Si noti che solo le righe della matrice vengono mescolate.

In [60]:
vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))

array([3, 4, 2, 5, 1])


In [61]:
np.random.shuffle(vec)
print(repr(vec))

array([5, 3, 4, 2, 1])


In [62]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


### Distributions
Usando `np.random` si può anche estrarre campioni da distribuzioni di probabilità. <br>Per esempio `np.random.uniform` si può usare per estarre numeri reali pseudo-casuali da una distribuzione uniforme.

In [63]:
print(np.random.uniform())

0.3132735169322751


In [64]:
print(np.random.uniform(low=-1.5, high=2.2))

0.4408281904196243


In [65]:
print(repr(np.random.uniform(size=3)))

array([0.44345289, 0.22957721, 0.53441391])


In [66]:
print(repr(np.random.uniform(low=-3.4, 
                             high=5.9,
                             size=(2, 2))))

array([[5.09984683, 0.85200471],
       [0.60549667, 5.33388844]])


La funzione `np.random.uniform` non ha argomenti richiesti.
<br>Le keyword `low` e `high` rappresentano il range da cui estrarre campioni casuali.<br>Poichè come valore di default hanno 0.0 e 1.0, il range di default sarà [0, 1).
<br> L'argomento di `size` è lo stesso per quello di `np.random.randint`.
<br><br>Un'altra distribuzione disponibile è quella `gaussiana` usando la funzione `np.random.normal`.

In [67]:
print(np.random.normal())

0.7252740646272712


In [68]:
print(np.random.normal(loc=1.5, scale=3.5))

4.772112039383628


In [69]:
print(repr(np.random.normal(loc=-2.4, 
                            scale=4.0,
                            size=(2, 2))))

array([[ 2.07318791, -2.17754724],
       [-0.89337346, -0.89545991]])


Come `np.random.uniform`, `np.random.normal` non richiede argomenti.
<br>Gli argomenti delle keyword `loc` e `scale` rappresentano rispettivamente la `deviazione standard` e la `media` della distribuzione.

### Custom sampling
NumPy permette anche di campionare da una distribuzione personalizzata con la funzione `np.random.choice`.

In [70]:
colors = ['red', 'blue', 'green']

In [71]:
print(np.random.choice(colors))

green


In [72]:
print(repr(np.random.choice(colors, size=2)))

array(['blue', 'red'], dtype='<U5')


In [73]:
print(repr(np.random.choice(colors, size=(2, 2),
                            p=[0.8, 0.19, 0.01])))

array([['red', 'red'],
       ['blue', 'red']], dtype='<U5')


L'argomento richiesto per `np.random.choice` è la probalità personalizzata da cui verranno estratti i valori. Il totale degli elementi in `p` deve essere `1`.

### Time to Code!
- setta `random1` uguale a `np.random.randint` con 5 come argomento
- setta `random_arr` uguale a `np.random.randint` con `3` come primo argomento, `10` come valore di `high` e `(3, 5)` come argomento di `size`.

In [74]:
random1 = np.random.randint(5)
random1

4

In [75]:
random_arr = np.random.randint(3, 
                               high=10, 
                               size=(3, 5))
random_arr

array([[3, 4, 6, 7, 5],
       [7, 3, 8, 6, 4],
       [5, 3, 7, 4, 5]])

- setta `random_uniform` uguale a `np.random_uniform` con `low` e `high` uguali a `-2.5` e a `1.5`. `size` uguale a `5`.

In [76]:
random_uniform = np.random.uniform(low=-2.5, 
                                   high=1.5, 
                                   size=5)
random_uniform


array([ 0.65711731, -2.08709597, -0.7084259 ,  1.13438201, -1.32554341])

- setta `random_norm` uguale a `np.random_normal` con `loc` e `scale` uguali a `2.0` e a `3.5`. `size` uguale a `(10, 5)`.

In [77]:
random_norm = np.random.normal(loc=2.0, 
                               scale=3.5, 
                               size=(10, 5))
random_norm

array([[-0.42081263,  0.61136266, -0.40510445, -0.95821975, -0.34936146],
       [ 1.9556739 , -1.91058622,  2.82045494,  7.80930762,  4.59715456],
       [ 1.32857557, -1.10670137, -0.61505403,  7.9235911 ,  2.17782714],
       [-0.22948476,  2.6682042 ,  9.35089298,  2.42055633,  4.16021088],
       [ 3.05059612,  0.76712554, -1.99881369,  0.77730047,  1.26887018],
       [ 4.05318117,  4.93644195,  5.25885728,  2.99955564,  5.09799407],
       [-0.64039279,  6.38503854,  3.79525437,  0.95667508,  3.70981351],
       [ 1.735499  ,  5.96070286,  7.31935886,  9.64951392, -2.88773717],
       [-3.05439832,  0.23436948,  2.56012974,  5.06659122,  3.10472232],
       [-5.07770426,  0.92828596,  4.89791125,  2.80533157,  4.66703913]])

- creare una lista con `'a'`, `'b'`, `'c'`, `'d'`.
- probabilità = `[0.5, 0.1, 0.2, 0.2]`
- setta `choice` uguale a `np.random_choice` con `choice` come promp argomento e specificano le probabilità sopra dichiarate con `p`.

In [78]:
choices = ['a', 'b', 'c', 'd']
choice = np.random.choice(choices, 
                          p=[0.5, 0.1, 0.2, 0.2])
choice

'a'

- setta `arr` uguale a un array che va da `1` a `5`
- applicare `np.random.shuffle` ad `arr`.

In [79]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)

## Indexing
### Array accessing
Accedere agli array di NumPy è la stessa cosa delle liste di Python. <br>Per gli array multidimensionali la modalità la medesima dell'accesso agli elementi delle liste di liste

In [80]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

1
5


In [81]:
arr = np.array([[6, 3], [0, 2]])
# Subarray
print(repr(arr[0]))

array([6, 3])


### Slicing
NumPy supporta anche lo slicing. Similmente a Python si usa l'operatore `:`, `arr[:]`, per lo slicing. <br>Si può anche usare l'indicizzazione negativa per slittare nella direzione inversa.

In [82]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [83]:
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


Per gli array multidimensionali, possiamo usare una `virgola` per separare le sezioni in ogni dimensione.

In [84]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


### Argmin and argmax
Oltre ad accedere ed effetuare lo slicing, è utile capire gli indici effettivi dell'elemento minimo e massimo.
Per fare questo si possono usare le funzioni `np.argmin` e `np.argmax`

In [86]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
arr

array([[-2, -1, -3],
       [ 4,  5, -6],
       [-3,  9,  1]])

In [87]:
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))

2
1
5


Le funzioni `np.argmin` e `np.argmax` hanno gli stessi argomenti. <br>
L'argomento richiesto è la matrice di input e l'argomento della keyword `axis` che specifica la dimensione su cui applicare l'operazione.

In [88]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
arr

array([[-2, -1, -3],
       [ 4,  5, -6],
       [-3,  9,  1]])

In [89]:
# l'indice dell'elemento di riga minimo per ogni colonna
print(repr(np.argmin(arr, axis=0)))

array([2, 0, 1], dtype=int64)


In [90]:
# l'indice dell'elemento di colonna minimo per ogni riga
print(repr(np.argmin(arr, axis=1)))

array([2, 2, 0], dtype=int64)


In [91]:
# applcata all'ultima dimensione
print(repr(np.argmax(arr, axis=-1)))

array([1, 1, 1], dtype=int64)


### Time to Code!
-  setta `elem` uguale al secondo al terzo elemento per riga

In [92]:
def direct_index(data):
    elem = data[1][2]
    return elem

- setta `slice1` che deve contenere tutte le righe ma saltare ogni primo elemento di ogni riga
- setta `slice2` che deve contenere tutti gli elementi delle tre righe ad eccezione degli ultimi due elementi.

In [93]:
def slice_data(data):
    slice1 = data[:, 1:]
    slice2 = data[0:3, :-2]
    return slice1, slice2

- trovare gli indici dei valori minimi
- setta `argmin_all` uguale a `argmin_min` con `data` come argomento
- setta `argmin1` uguale a `np.argmin` con `data` come primo argomento e specificando il valore della keyword `axis`

In [94]:
def argmin_data(data):
    argmin_all = np.argmin(data)
    argmin1 = np.argmin(data, 
                        axis=1)
    return argmin_all, argmin1

- trovare gli indici dei valori massimo per ogni riga
- settare `argmax_neg1` uguale `argmax_neg` con `data` come primo argomento e `-1` come elemento della keyword `axis`

In [95]:
def argmax_data(data):
    argmax_neg1 = np.argmax(data, 
                            axis=-1)
    return argmax_neg1

## Filtering
### Filtering data
La chiave per filtrare i dati è attraverso operazioni di relazione di base, ad esempio `==`, `>`, `ecc.` 
<br>In NumPy, possiamo applicare operazioni di relazione di base in termini di elementi su matrici.
<br>L'operatore `~`rappresenta la negazione booleana.

In [96]:
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])
arr

array([[ 0,  2,  3],
       [ 1,  3, -6],
       [-3, -2,  1]])

In [97]:
print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))
# Negated from the previous step
print(repr(~(arr != 1)))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


`np.nan` non può essere utilizzato con alcuna operazione di relazione. Quindi si usa `np.isnan`.

In [98]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
arr

array([[ 0.,  2., nan],
       [ 1., nan, -6.],
       [nan, -2.,  1.]])

In [99]:
print(repr(np.isnan(arr)))

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


Il modo in cui si esegue il filtraggio stesso è attraverso la funzione `np.where`.

### Filtering in NumPy
`np.where` accetta un primo argomento, che è una matrice booleana che rappresenta le posizioni degli elementi per cui vogliamo filtrare.
<br><br>La tupla avrà una dimensione uguale al numero di dimensioni nei dati e ogni matrice rappresenta gli indici `True` per la dimensione corrispondente. 

In [100]:
print(repr(np.where([True, False, True])))

(array([0, 2], dtype=int64),)


In [101]:
arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

(array([1, 3], dtype=int64),)


In [102]:
arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])
x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind)) # x indices of non-zero elements
print(repr(y_ind)) # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))

array([0, 0, 1, 2], dtype=int64)
array([1, 2, 0, 0], dtype=int64)
array([ 2,  3,  1, -3])


`np.where` può essere usata anche con 3 argomenti. Il secondo e il terzo argomento rappresentano i rimpiazzamenti se la condizione è `True` o `False`.

In [103]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
negatives = np.array([[-2, -5], [-1, -8]])

In [104]:
print(repr(np.where(np_filter, positives, negatives)))

array([[ 1, -5],
       [-1,  4]])


In [105]:
np_filter = positives > 2
print(repr(np.where(np_filter, positives, negatives)))

array([[-2, -5],
       [ 3,  4]])


In [106]:
np_filter = negatives > 0
print(repr(np.where(np_filter, positives, negatives)))

array([[-2, -5],
       [-1, -8]])


Se si volesse utilizzare un valore di sostituzione costante, `-1` si potrebbe incorporare un `broadcasting`.

In [107]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])

In [108]:
print(repr(np.where(np_filter, positives, -1)))

array([[ 1, -1],
       [-1,  4]])


### Axis-wise filtering
Se si volesse fitrare su una singola riga o colonna di dati, ci sono le funzioni `np.any` e `np.all`. Le funzioni restituiscono una matrice booleana.

In [109]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
arr

array([[-2, -1, -3],
       [ 4,  5, -6],
       [ 3,  9,  1]])

In [110]:
print(repr(arr > 0))
print(np.any(arr > 0))
print(np.all(arr > 0))

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
True
False


la funzione `np.any` equivale all'esecuzione di un OR logico (`||`), mentre la funzione `np.all` equivale a un AND logico (`&&`) sul primo argomento.
<br><br>Quando viene passato un solo argomento, la funzione viene applicata all'intera matrice di input, quindi il valore restituito è un singolo.<br><br>Se si utilizza un input multidimensionale e si specifica l'argomento della keyword `àxis` l'output sarà una matrice.
<br>Gli argomenti di `axis` sono gli stessi descritti per le funzioni `np.argmin` e `np.argmax`

In [111]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
arr

array([[-2, -1, -3],
       [ 4,  5, -6],
       [ 3,  9,  1]])

In [112]:
print(repr(arr > 0))
print(repr(np.any(arr > 0, axis=0)))
print(repr(np.any(arr > 0, axis=1)))
print(repr(np.all(arr > 0, axis=1)))

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
array([ True,  True,  True])
array([False,  True,  True])
array([False, False,  True])


`np.any` e `np.all` si possono utilizzare contemporaneamente a `np.where`

In [113]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
arr

array([[-2, -1, -3],
       [ 4,  5, -6],
       [ 3,  9,  1]])

In [114]:
has_positive = np.any(arr > 0, axis=1)
print(has_positive)
print(repr(arr[np.where(has_positive)]))

[False  True  True]
array([[ 4,  5, -6],
       [ 3,  9,  1]])


### Time to Code!

- setta `x_ind, y_ind` uguale a `np.where` applicata con la condizione `data>0`

In [115]:
def get_positives(data):
    x_ind, y_ind = np.where(data > 0)
    return data[x_ind, y_ind]

- setta `zeros` uguale a `np.zeros_like` con `data` come argomento
- setta `zero_replace` uguale a `np.where` con la condizione `data>0`; il secondo argomento sarà `data` e il terzo sarà `zeros`.

In [116]:
def replace_zeros(data):
    zeros = np.zeros_like(data)
    zero_replace = np.where(data > 0, data, zeros)
    return zero_replace

- setta `neg_one_replace` uguale a `np.where` con la condizione `data>0`; il secondo argomento sarà `data` e il terzo sarà `-1`.

In [117]:
def replace_neg_one(data):
    neg_one_replace = np.where(data > 0, data, -1)
    return neg_one_replace

- setta `coin_flips` uguale a `np.where` con la condizione `np.random.randint` con `2` come primo argomento e `datashape` come argomento della keyword `size`.
- setta `bool_coin_flips` uguale a `coin_flips` castato `np.bool` con la funzione `np.astype`.
- setta `one_replace` uguale a `np.where` con `bool_coin_flips`, `data`, e `1`.

In [118]:
def coin_flip_filter(data):
    coin_flips = np.random.randint(2, size=data.shape)
    bool_coin_flips = coin_flips.astype(np.bool)
    one_replace = np.where(bool_coin_flips, data, 1)
    return one_replace

## Statistics
### Analysis
Per esempio, si può ottenere valori minimi e massimi di un array NumPy usando le funzioni `min` e `max`.
<br>Gli argomenti di `axis` sono gli stessi descritti per le funzioni `np.argmin` e `np.argmax`

In [119]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
arr

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [120]:
print(arr.min())
print(arr.max())

-60
72


In [121]:
print(repr(arr.min(axis=0)))
print(repr(arr.max(axis=-1)))

array([ -3,  -2, -60])
array([72,  3,  4])


### Statistical metrics
Numpy fornisce anche funzioni statistiche per calcolare per esempio la media, la varianza e la mediana: `np.mean`, `np.var`, `np.median`.
<br> `np.median` applicata senza considerare `axis` prende la mediana della matrice appiattita.

In [122]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
arr

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [123]:
print(np.mean(arr))
print(np.var(arr))
print(np.median(arr))
print(repr(np.median(arr, axis=-1)))

2.0
977.3333333333334
1.0
array([ 3.,  1., -2.])


https://numpy.org/doc/stable/reference/routines.statistics.html

### Time to Code!

- setta `overall_min` uguale a `data.min` applicata senza argomenti
- setta `overall_max` uguale a `data.max` applicata senza argomenti

In [124]:
def get_min_max(data):
    overall_min = data.min()
    overall_max = data.max()
    return overall_min, overall_max

- setta `min0` uguale a `data.min` con `0` come argomento della keyword `axis`

In [125]:
def col_min(data):
    min0 = data.min(axis=0)
    return min0

- setta `mean` uguale a `np.mean` applicato a `data`
- setta `median` uguale a `np.median` applicato a `data`
- setta `var` uguale a `np.var` applicato a `data`

In [126]:
def basic_stats(data):
    mean = np.mean(data)
    median = np.median(data)
    var = np.var(data)
    return mean, median, var

## Aggregation
### Summation
La funzione `np.sum` accetta un array NumPy come argomento obbligatorio e utilizza la keyword `axis`.
<br>Se l'argomento della parola chiave non è specificato, `np.sum` restituisce la somma complessiva della matrice.

In [127]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
arr

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [128]:
print(np.sum(arr))
print(repr(np.sum(arr, axis=0)))
print(repr(np.sum(arr, axis=1)))

18
array([ -2,  73, -53])
array([ 75, -56,  -1])


In aggiunta alla classica somma, NumPy può calcolare la somma cumulata usando `np.cumsum`. Come `np.sum`, `np.cumsum` richiede un argomento e usa `axis`.
<br>Se l'argomento della keyword `axis` non è specificato, verranno restituite le somme cumulative per la matrice appiattita

In [129]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
arr

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [130]:
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis=0)))
print(repr(np.cumsum(arr, axis=1)))

array([ 0, 72, 75, 76, 79, 19, 16, 14, 18], dtype=int32)
array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]], dtype=int32)
array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]], dtype=int32)


### Concatenation
In NumPy, concatenare equivale a combinare più array in uno. La funzione che utilizziamo per farlo è `np.concatenate`. 
Come le funzioni della somma, `np.concatenate` usa l'argomento della keyword `axis`. Tuttavia, il valore predefinito per `axis` è `0`.

In [131]:
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr1

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4]])

In [132]:
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])
arr2

array([[-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])

In [133]:
print(repr(np.concatenate([arr1, arr2])))
print(repr(np.concatenate([arr1, arr2], axis=1)))
print(repr(np.concatenate([arr2, arr1], axis=1)))

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])


### Time to Code!

- setta `total_sum` uguale a `np.sum` applicato a `data`
- setta `col_sum` uguale a `np.sum` applicato a `data` con `axis` uguale a 0

In [134]:
def get_sums(data):
    total_sum = np.sum(data)
    col_sum = np.sum(data, axis=0)
    return total_sum, col_sum

- setta `row_cumsum` uguale a `np.cumsum` applicato a `data` con `axis` uguale a `1`

In [135]:
def get_cumsum(data):
    row_cumsum = np.cumsum(data, axis=1)
    return row_cumsum

- setta `col_concat` uguale a `np.concatenate` applicato alla lista `data1` e `data2`
- setta `row_concat` uguale a `np.concatenate` applicato a `data` con `axis` uguale a `1`

In [136]:
def concat_arrays(data1, data2):
    col_concat = np.concatenate([data1, data2])
    row_concat = np.concatenate([data1, data2], axis=1)
    return col_concat, row_concat

## Saving Data
### Saving
Dopo aver eseguito la manipolazione dei dati con NumPy, si usa salvare i dati in un file per un uso futuro. Si utilizza la funzione `np.save`.
<br>Il primo argomento per la funzione `np.save` è il nome/percorso del file in cui vogliamo salvare i nostri dati. 
<br>Il nome/percorso del file deve avere l'estensione `".npy"`. 
<br>Il secondo argomento per la funzione `np.save` sono i dati NumPy che vogliamo salvare.
<br><br>La funzione non ha nessun valore restituito. Se il file `.npy` viene chiamato con lo stesso nome di un file già esistente, quest'ultimo verrà sovrascritto.

In [137]:
arr = np.array([1, 2, 3])
# Saves to 'arr.npy'
np.save('arr.npy', arr)
# Also saves to 'arr.npy'
np.save('arr', arr)

### Loading
Dopo aver salvato i dati li si possono ricaricare usando `np.load`.<br>La funzione richiede come argomento il nome/percorso che contiene i dati salvati. Ritornerà i dati che sono stati salvati.

In [138]:
arr = np.array([1, 2, 3])
np.save('arr.npy', arr)
load_arr = np.load('arr.npy')
print(repr(load_arr))

# Will result in a FileNotFoundError: If we uncomment line 7 and run again.
#load_arr = np.load('arr')

array([1, 2, 3])


### Time to Code!

- setta `points` uguale a `np.random.uniform`, con `low` e `high` uguali a `-2.5` e a `2.5`. Avrà `size` uguale a `(100, 2)`.
- salva il file

In [139]:
def save_points(save_file):
    points = np.random.uniform(
        low=-2.5, 
        high=2.5, 
        size=(100, 2))
    np.save(save_file, points)